#!/bin/bash
cp -av ~/.vim/ftplugin/{h.vim,cpp.vim,c.snip,vim.vim} vim/ftplugin/
cp -av ~/.vim/scripts.vim vim/
cp -av ~/.vim/after/syntax/*.vim vim/after/syntax/
cp -av ~/.vimrc vim/
cp -av ~/.inputrc tools/
cp -av ~/bin/{a,c,colorpwd} tools/
