#!/bin/bash
cp -v ~/.vim/ftplugin/{h.vim,cpp.vim,c.snip,vim.vim} vim/ftplugin/
cp -v ~/.vim/scripts.vim vim/
cp -v ~/.vim/after/syntax/*.vim vim/after/syntax/
cp -v ~/.vimrc vim/
cp -v ~/.inputrc tools/
cp -v ~/bin/{a,c,colorpwd} tools/
